### PR TITLE
Improve Windows Build and AppVeyor Artifacts

### PR DESCRIPTION
**Pull request by bchavez**
Hello,

I've modified the build scripts to save the compilation results of the Windows `Release` builds on AppVeyor. This will help facilitate testing as not everyone has local build tools installed on their machines. Now, you can just point them to the latest build artifact to test the most recent build.

This PR includes:

### Update TAP-9 Driver

The Windows TAP-9 driver from OpenVPN hasn't been updated in a while.

* The current **FreeLAN** version in this repo is **9.0.0.9**.
* The current **OpenVPN** version is **9.0.0.21**.

This PR includes the latest TAP-9 driver from **OpenVPN** that is digitally signed. The problem I ran into testing the Windows build on **Windows 2012 R2** was when the installation appeared to have completed without error but silently failed. After digging deeper, I found the problem was due to the TAP-9 (`v9.0.0.9`) driver not having the required digital signatures.

Here's a screenshot of the issue:
vmware_2224
vmware_2228
vmware_2229

----

Using the latest **9.0.0.21** driver produces much better installation results:

vmware_2232

### TAP-9 Vulnerability
Secondly, keeping an old TAP-9 driver can raise some security concerns. Namely, there is an important security vulnerability note in **OpenVPN 2.4.6** download page worth keeping in mind:

> *Installer I601 included tap-windows6 driver 9.22.1 which had one security fix and dropped Windows Vista support. However, in installer I602 we had to revert back to tap-windows 9.21.2 due to driver getting reject on freshly installed Windows 10 rev 1607 and later when Secure Boot was enabled. The failure was due to the new, more strict driver signing requirements. The 9.22.1 version of the driver is in the process of getting approved and signed by Microsoft and will be bundled in an upcoming Windows installer.*
https://openvpn.net/community-downloads/

### ISS installer referencing missing `ssleay32.dll` and `libeay32.dll`
Both files `ssleay32.dll` and `libeay32.dll` are missing from the build outputs. So I removed them from the ISS installer script. I'm not sure where they went, but if they're required, let me know where I can find them and I'll be happy to revert that change.

I still need to do more testing, but I wanted to put this PR out here so y'all can review my changes. Please let me know your thoughts.

Also, if someone could help me with providing instructions on how to create a `.deb` installer file for **Ubuntu**, that would be great. I'm still struggling to find a reliable way to get an installer for **Ubuntu** (besides installing directly after build from source).

Thanks,
Brian

:crystal_ball: :dolls: ***["Magic and technology. Voodoo dolls and chants. Electricity. Were makin weird science..."](https://www.youtube.com/watch?v=Jm-upHSP9KU)***

### CODE REVIEW

**Comment by s-vincent** [comment]
Hi @bchavez!

Thanks you very much for this contribution!

One note: do we really need the buildartifacts as we already provide the setup ?
If yes maybe change its name to freelan-binary-x86/x64-gitrevision ? Same for setup artefact (freelan-setup-x86/x64-gitrevision).

Otherwise it looks good to me.
@ereOn your thoughts ?

**Comment by bchavez** [comment]
Hi @s-vincent ,

Thanks for the kind words!

I was thinking the same thing about `BuildArtifacts.zip` but there may be rare cases where having access to PDB files might be useful for debugging. Also, it may be convenient for some to the extract the contents of a ZIP without having to go through the ceremony of the installer to just to test a few things. Ultimately, it doesn't really cost us anything to ZIP `BuildArtifacts` on AppVeyor. IIRC, artifact storage on AppVeyor is automatically purged after 6 months.

On a side note: I did want to make a change to ISS script to use x64 and x86 (IE: changing `--arch=amd64` to `---arch=x86`) to avoid adding the extra `INSTALLER_BITS` environment variable. But I dunno, let me know if that makes sense.

Also, do you know how I can generate a `.deb`/Ubuntu file from source?

Thanks,
Brian

**Comment by ereOn** [comment]
@bchavez This is an amazing contribution. Thank you so much! I really appreciate it.

I'm also in favor of keeping the artifacts (especially the .pdb, for the very reason you mentioned). In any case, it doesn't cost much.

You can generate .deb files with `dpkg-deb --build` easily. I don't think those will be "official" though, especially as they won't be signed nor be published in the Debian's repositories. But it's definitely a good thing for developers out there eager to test new versions.

**Comment by bchavez** [comment]
Thanks @ereOn !

I tried the `dpkg-deb --build` command, but I get:
```
root@test:~/freelan21/freelan# ls
apps          build       CONTRIBUTING.md       defines.pyc      gpl-
appveyor.yml  BUILD.md    defines.hpp.template  freelan-all.sln  libs
artwork       config.log  defines.py            fscp.txt         LICE

root@test:~/freelan21/freelan# dpkg-deb --build
dpkg-deb: error: --build needs a <directory> argument

Type dpkg-deb --help for help about manipulating *.deb files;
Type dpkg --help for help about installing and deinstalling packages.
root@test:~/freelan21/freelan#
```
Do I run `dpkg-deb --build` in the root of the checkout folder? Or do I do this in `/build/release`? Any help would be great. I'm really new to deb packaging; I apologize. :cry: 

Also, this PR isn't quite ready (please don't merge yet). I have to verify a few more things but waiting on build results. I'll post a comment when I think it's ready to go!

**Comment by s-vincent** [comment]
@ereon @bchavez I guess ```dpkg-deb --build``` uses debian specific directory (with control file, ...). This directory is not part of the master branch anymore.

@leggewie maintains a separate branch for debian packaging. He doesn't think having "unofficial" debian packages good (see #147).

**Comment by bchavez** [comment]
Thanks @s-vincent for the information! I will look for the branch that @leggewie has. I only want to create a `.deb` file to make deployment and testing internally on multiple machines easier.

I don't want to step on anyone's toes but I think it's a good idea to have some simple way to "generate" a `.deb` file easily for testing in `/master`. One maintenance issue is branches get out of date from `/master` and even worse, merge conflicts and control files could be a headache to resolve if something breaks upstream. Especially for me with limited knowledge of freelan's source code.

It would really be great if I could just `$issuesome command` and I get an unofficial `deb` file for testing `freelan-2.1-githash-testing.deb`. It really goes a long way for testing! :+1:

**Comment by bchavez** [comment]
Hello!

This PR is now ready. The build matrix is green and the artifact results are here:
https://ci.appveyor.com/project/bchavez/freelan/builds/19535610

As requested @s-vincent , the build artifacts now follow your suggested naming convention:

`Release` configs have 2 artifacts:
```
freelan-binary-x64-61618c08.zip
freelan-setup-x64-61618c08.exe
```
`Debug` configs have 1 artifact:
```
freelan-binary-x64-61618c08.zip
```
This is fantastic. Thank you. It is MUCH easier to test now builds now.

Please merge at the earliest convenience. :heart: 

Also, would be great if we could have AppVeyor's build checks appear in PR threads in this repo. Right now, AppVeyor's build status isn't hooked up via GitHub/WebHooks and is under a somewhat hidden project under `ereOn/azmq`. I'm not sure this helps us validating if our PRs are okay.

I have another PR inbound that fixes `DeviceIoControl` tap driver control codes. Seems like the **FreeLAN** `asiotap` is sending an invalid parameter to the TAP device driver. I will send the PR soon as I'm done tracking down the issue.

Thanks,
Brian

:walking_man: :walking_woman: **[Missing Persons - Walking in L.A.](https://www.youtube.com/watch?v=R_UpLtGEWoY)**

**Comment by s-vincent** [comment]
> AppVeyor recently did a re-design of their UX to make organizations work better. Maybe it's a good time to take a second look?

I don't have access to the freelan project configuration section. @ereOn, can you have a look when you will have some time ?

**Comment by bchavez** [comment]
On a happy side note, was able to get a `.deb` file. Took me a few days to gork `.deb` packing but for those interested (and for my personal notes):

1. Git clone the repo.
1. Git checkout `debian/unstable` branch.
   * `git checkout origin/debian/unstable`
2. Rebase `debian/unstable` on top of `/master`.
   * `git rebase master`
3. Edit `debian/rules` and add the following line to the end of the `rules` file:
   * `override_dh_usrlocal:`
4. Execute `dh binary` in `freelan` root checkout folder. Wait a long time, freelan will build. Then out comes a cute `.deb` file! hey! :)

If you want to make changes, test, and deploy those changes on other machines in the form of `.deb` files, `dh clean` and `dh binary` are your friend on the build machine. Ultimately, to get the startup service working requires fidgeting around with startup files until it works.

**Comment by ereOn** [comment]
@s-vincent & @bchavez I updated AppVeyor's configuration to grant wider permissions and allow access to the Github team.

Let me know if that's enough!

**Comment by s-vincent** [comment]
Thanks @ereOn, appveyor build link is now displayed on commits page with TravisCI ones.

**Pull request merged**
