### PR TITLE
Add support for OpenWRT

### PR DESCRIPTION
**Pull request by leggewie**
untested work to build freelan on openwrt provided courtesy of @champtar

### CODE REVIEW

**Comment by champtar** [comment]
hi @ereOn @leggewie,
sorry for not jumping in sooner
i've a more up to date makefile, i'll send it soon

**Comment by leggewie** [comment]
let's actually try to push this to https://github.com/openwrt/packages

**Comment by champtar** [comment]
@leggewie, please push this to openwrt :)
http://pastebin.com/xdyUwaBc

**Comment by ereOn** [comment]
@champtar Thanks !

@leggewie Can you please update the PR with the new files and add a reference to the PR in [openwrt](https://github.com/openwrt/packages) in this thread ?

**Comment by leggewie** [comment]
what does PR mean in this case?  I only know PR as public relations ;-)

**Comment by ereOn** [comment]
@leggewie Sorry ;)

That means **P**ull **R**equest.

**Comment by leggewie** [comment]
I see.

Will do as requested.

**Comment by leggewie** [comment]
I pushed the updated information to the branch.  Now I tried to actually build the package.  But it doesn't show up under `make menuconfig` (this is the openwrt build system) and then I look under Network-VPN which is where I guess it would show up.  What's missing?

    $ ./scripts/feeds search freelan
    Search results in feed 'local':
    freelan2                 	highly-configurable peer-to-peer VPN software

**Comment by champtar** [comment]
You need to run ./scripts/feeds update -a  and also ./scripts/feeds install
.....

**Comment by leggewie** [comment]
I did that, but it still won't show up.  I believe the ./scripts/feeds search freelan" wouldn't show the package unless I had done so.

**Comment by ereOn** [comment]
@leggewie @champtar Can you guys let me know when this is complete so I can merge it/close the ticket ?

I don't have enough OpenWRT knowledge to know for sure on my own.

**Comment by leggewie** [comment]
@champtar can you successfully compile the package? does it run successfully?  I have found how to build the package even when it doesn't show up in `make menuconfig` but for me even boost as supplied by upstream fails to build as of now.  I don't want to push untested stuff.

**Comment by leggewie** [comment]
I've pushed this to https://github.com/openwrt/packages/pull/1657 now.

**Comment by ereOn** [comment]
@leggewie Awesome ! Thanks.

**Pull request closed without merging**
